### ISSUE TITLE
License of some modules

### ISSUE THREAD

**Issue by luisapace** [jest-community/jest-editor-support#11]
Hi, my team would use jest-editor support and to approve that I've to verify all its licenses.

Now I've seen that some modules (i.e.  jest-editor-support/src/__tests__/snapshot.test.js) show this header:
 **_* This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory._**

other modules instead refers to MIT license, but in the root directory of the source I cannot see any license file.

Could you please clarify me what are the licenses? 

Thanks for your support on this.

**Comment by connectdotz** [comment]
hmmm... I saw some files still have facebook copyright, which is understandable since it was part of [jest](https://github.com/facebook/jest). But now it has been moved out to `jest-community`, should we update all the copyrights accordingly? @orta, what is the overall license policy for `jest-community`? I saw some repo using MIT, does that apply to this repo as well?

**Comment by orta** [comment]
I'm gonna cc in @cpojer for this one, FB copyrights are not something I'm going to take a guess on

**Comment by cpojer** [comment]
Change it to MIT.

**Comment by orta** [comment]
Fixed with #15

**Comment by luisapace** [comment]
Many thanks !

**Comment by luisapace** [comment]
Many thanks !
