### ISSUE TITLE
Typescript parameter decorator support

### ISSUE THREAD

**Issue by jbjhjm** [jest-community/jest-editor-support#89]
Hey everyone!

Typescript features 3 kinds of decorators - class-level, method-level and parameter-level.
Only the first two seem to be officially supported in babel 7 - https://babeljs.io/docs/en/babel-plugin-proposal-decorators
But there is a plugin available adding support for these - https://github.com/WarnerHooh/babel-plugin-parameter-decorator

So, I have just been investigating a error within a vscode extension, namely [vscode-jest-runner](https://github.com/firsttris/vscode-jest-runner) and it will fail to work correctly as soon as parameter decorators are used within jest-typescript files.
Issue here: https://github.com/firsttris/vscode-jest-runner/issues/260

Is it possible to register separate plugins to be included before executing parser?
If not, would you mind to include the plugin by default? 
Thanks!

**Comment by connectdotz** [comment]
@jbjhjm I take a look of these issue and found the following:

1. the current @babel/parser option "decorators", does not support parameter-decorator, looks like we need to switch to the "decorators-legacy" for this use case. (see [@babel/parser type](https://github.com/babel/babel/blob/c90add779ae6f096962bf0ec1add08a6893853f2/packages/babel-parser/typings/babel-parser.d.ts)) (Note: This package does not load the plugins because it only performs syntax tree parsing, not transformation. What matters here is the options we passed to @babel/parser)
2. that means we need to allow users to override these options at run time, i.e. need to change the API. Although I think we can make it backward compatible. (see [helper.ts](https://github.com/jest-community/jest-editor-support/blob/master/src/parsers/helper.ts) and [index.ts](https://github.com/jest-community/jest-editor-support/blob/master/src/parsers/index.ts))
3. we should also upgrade the @babel dependency to pick up the latest changes.

Anyway, it's doable and I could probably find some time to do this in the next few weeks. You can probably get it done sooner if you are interested in doing the PR yourself.

**Comment by jbjhjm** [comment]
thanks for checking it out @connectdotz ! Not sure if I find time any sooner than you, but will let you know here if I happen to start work on it!
